version: '3.8'

services:
  dev-db:
    image: postgres:15
    container_name: remember-dev-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: